version: '2'

services:
  workshop-app:
    image: workshop-app
    build: ./
    depends_on:
      - redis
    links:
      - redis
    environment:
      - REDIS_HOST=redis
    ports:
      - 9000:9000

  redis:
    image: redis
    restart: always
    expose:
      - 6379
